import type { ProductionJsonV4 } from "./types.js";
import { PRODUCTION_JSON_V4_SCHEMA } from "./types.js";

/**
 * Static wardrobe example for Production JSON v4 design validation.
 * Not used by runtime v3 export.
 */
export const productionJsonV4Example: ProductionJsonV4 = {
  schema: PRODUCTION_JSON_V4_SCHEMA,
  meta: {
    orderId: "RZM-EXAMPLE-V4-001",
    generator: "razmerno-production-v4-foundation",
    configVersion: "v4-foundation",
    createdAt: "2026-06-23T00:00:00.000Z",
    source: "design-example",
  },
  basisCompatibility: {
    target: "basis-mebelshchik",
    mode: "manual-json",
    status: "manual-json-ready",
    doesNotGenerateB3d: true,
    requiresTechnologist: true,
  },
  coordinateSystem: {
    unit: "mm",
    worldOrigin: "front-bottom-left",
    axes: {
      x: "left-to-right",
      y: "bottom-to-top",
      z: "front-to-back",
    },
    precisionMm: 0.1,
  },
  product: {
    type: "wardrobe",
    widthMm: 1800,
    heightMm: 2460,
    depthMm: 600,
    heightIncludesSupportMm: true,
  },
  rules: {
    materials: {
      body: { kind: "ldsp", thicknessMm: 16, locked: true },
      facade: { ldspThicknessMm: 16, mdfThicknessMm: 18 },
      hdf: { thicknessMm: 3 },
      drawerBottom: { kind: "hdf", thicknessMm: 3 },
    },
    edgeBanding: {
      bodyThicknessMm: 1,
      facadeThicknessMm: 2,
      bodyCoverage: "all-around",
      facadeCoverage: "all-around",
      hdfCoverage: "none",
    },
    facadeGapMm: 1.5,
    shelfFrontInsetMm: 30,
    bodyConstruction: "side-panels-on-bottom",
    topPanelPlacement: "between-sides",
    pairedFacadePolicy: {
      centerGapMm: 3,
      sideGapMm: 1.5,
    },
    textureDirectionPolicy: "longest-panel-side",
    hdfTextureDirection: "none",
  },
  materials: [
    {
      id: "mat-body-white-ldsp-16",
      kind: "ldsp",
      producer: "Egger",
      article: "W960",
      decorName: "Белый матовый",
      thicknessMm: 16,
      sheetWidthMm: 2800,
      sheetHeightMm: 2070,
      unit: "m2",
      textureDirection: "vertical",
      grainAxis: "y",
      grainLocked: true,
      source: "seed",
    },
    {
      id: "mat-facade-mdf-18",
      kind: "mdf",
      decorName: "МДФ фасад",
      thicknessMm: 18,
      textureDirection: "vertical",
      grainAxis: "y",
      source: "seed",
    },
    {
      id: "mat-hdf-white-3",
      kind: "hdf",
      decorName: "ХДФ белый",
      thicknessMm: 3,
      textureDirection: "none",
      grainAxis: "none",
      source: "seed",
    },
    {
      id: "edge-white-abs-1mm",
      kind: "ldsp",
      decorName: "ABS кромка 1 мм",
      thicknessMm: 1,
      textureDirection: "none",
      source: "manual",
    },
    {
      id: "edge-white-abs-2mm",
      kind: "ldsp",
      decorName: "ABS кромка 2 мм",
      thicknessMm: 2,
      textureDirection: "none",
      source: "manual",
    },
  ],
  panels: [
    {
      id: "panel-bottom",
      objectType: "panel",
      basisObjectType: "panel",
      role: "bottom",
      name: "Дно",
      article: "BD-BOTTOM",
      materialRef: "mat-body-white-ldsp-16",
      materialKind: "ldsp",
      thicknessMm: 16,
      dimensions: { widthMm: 1768, heightMm: 600, thicknessMm: 16 },
      position: { xMm: 16, yMm: 60, zMm: 0 },
      orientation: { basisPanelKind: "horizontal", plane: "XZ", normalAxis: "Y" },
      faceSide: "top",
      textureDirection: "horizontal",
      includeInDocumentation: true,
      edgeBandingRefs: ["edge-bottom-front", "edge-bottom-back", "edge-bottom-left", "edge-bottom-right"],
    },
    {
      id: "panel-side-left",
      objectType: "panel",
      basisObjectType: "panel",
      role: "side-left",
      name: "Боковина левая",
      article: "BD-SIDE-L",
      materialRef: "mat-body-white-ldsp-16",
      materialKind: "ldsp",
      thicknessMm: 16,
      dimensions: { widthMm: 600, heightMm: 2384, thicknessMm: 16 },
      position: { xMm: 0, yMm: 76, zMm: 0 },
      orientation: { basisPanelKind: "vertical", plane: "YZ", normalAxis: "X" },
      faceSide: "inner",
      textureDirection: "vertical",
      includeInDocumentation: true,
      edgeBandingRefs: ["edge-side-left-front", "edge-side-left-back", "edge-side-left-top", "edge-side-left-bottom"],
    },
    {
      id: "panel-side-right",
      objectType: "panel",
      basisObjectType: "panel",
      role: "side-right",
      name: "Боковина правая",
      article: "BD-SIDE-R",
      materialRef: "mat-body-white-ldsp-16",
      materialKind: "ldsp",
      thicknessMm: 16,
      dimensions: { widthMm: 600, heightMm: 2384, thicknessMm: 16 },
      position: { xMm: 1784, yMm: 76, zMm: 0 },
      orientation: { basisPanelKind: "vertical", plane: "YZ", normalAxis: "X" },
      faceSide: "inner",
      textureDirection: "vertical",
      includeInDocumentation: true,
      edgeBandingRefs: ["edge-side-right-front", "edge-side-right-back", "edge-side-right-top", "edge-side-right-bottom"],
    },
    {
      id: "panel-top",
      objectType: "panel",
      basisObjectType: "panel",
      role: "top",
      name: "Крышка",
      article: "BD-TOP",
      materialRef: "mat-body-white-ldsp-16",
      materialKind: "ldsp",
      thicknessMm: 16,
      dimensions: { widthMm: 1768, heightMm: 600, thicknessMm: 16 },
      position: { xMm: 16, yMm: 2460, zMm: 0 },
      orientation: { basisPanelKind: "horizontal", plane: "XZ", normalAxis: "Y" },
      faceSide: "bottom",
      textureDirection: "horizontal",
      includeInDocumentation: true,
      edgeBandingRefs: ["edge-top-front", "edge-top-back", "edge-top-left", "edge-top-right"],
    },
    {
      id: "panel-back",
      objectType: "panel",
      basisObjectType: "panel",
      role: "back-panel",
      name: "Задняя стенка",
      article: "BD-BACK",
      materialRef: "mat-hdf-white-3",
      materialKind: "hdf",
      thicknessMm: 3,
      dimensions: { widthMm: 1768, heightMm: 2384, thicknessMm: 3 },
      position: { xMm: 16, yMm: 76, zMm: 597 },
      orientation: { basisPanelKind: "frontal", plane: "XY", normalAxis: "Z" },
      faceSide: "inner",
      textureDirection: "none",
      includeInDocumentation: true,
    },
    {
      id: "panel-shelf-1",
      objectType: "panel",
      basisObjectType: "panel",
      role: "shelf",
      name: "Полка 1",
      article: "BD-SHELF-1",
      materialRef: "mat-body-white-ldsp-16",
      materialKind: "ldsp",
      thicknessMm: 16,
      dimensions: { widthMm: 860, heightMm: 554, thicknessMm: 16 },
      position: { xMm: 16, yMm: 1200, zMm: 30 },
      orientation: { basisPanelKind: "horizontal", plane: "XZ", normalAxis: "Y" },
      faceSide: "top",
      textureDirection: "horizontal",
      frontInsetMm: 30,
      includeInDocumentation: true,
      edgeBandingRefs: [
        "edge-shelf-1-front",
        "edge-shelf-1-back",
        "edge-shelf-1-left",
        "edge-shelf-1-right",
      ],
    },
    {
      id: "panel-facade-left",
      objectType: "panel",
      basisObjectType: "panel",
      role: "facade-door",
      name: "Фасад левый",
      article: "FC-LEFT",
      materialRef: "mat-facade-mdf-18",
      materialKind: "mdf",
      thicknessMm: 18,
      dimensions: { widthMm: 894, heightMm: 2397, thicknessMm: 18 },
      position: { xMm: 1.5, yMm: 61.5, zMm: -18 },
      orientation: { basisPanelKind: "frontal", plane: "XY", normalAxis: "Z" },
      faceSide: "outer",
      textureDirection: "vertical",
      facadeGaps: { topMm: 1.5, rightMm: 1.5, bottomMm: 1.5, leftMm: 1.5 },
      pairedFacadeCenterGapMm: 3,
      includeInDocumentation: true,
      hardwareRefs: ["hardware-hinge-left-1", "hardware-hinge-left-2"],
      edgeBandingRefs: [
        "edge-facade-left-top",
        "edge-facade-left-right",
        "edge-facade-left-bottom",
        "edge-facade-left-left",
      ],
    },
    {
      id: "panel-facade-right",
      objectType: "panel",
      basisObjectType: "panel",
      role: "facade-door",
      name: "Фасад правый",
      article: "FC-RIGHT",
      materialRef: "mat-facade-mdf-18",
      materialKind: "mdf",
      thicknessMm: 18,
      dimensions: { widthMm: 894, heightMm: 2397, thicknessMm: 18 },
      position: { xMm: 898.5, yMm: 61.5, zMm: -18 },
      orientation: { basisPanelKind: "frontal", plane: "XY", normalAxis: "Z" },
      faceSide: "outer",
      textureDirection: "vertical",
      facadeGaps: { topMm: 1.5, rightMm: 1.5, bottomMm: 1.5, leftMm: 1.5 },
      pairedFacadeCenterGapMm: 3,
      includeInDocumentation: true,
      hardwareRefs: ["hardware-hinge-right-1", "hardware-hinge-right-2"],
      edgeBandingRefs: [
        "edge-facade-right-top",
        "edge-facade-right-right",
        "edge-facade-right-bottom",
        "edge-facade-right-left",
      ],
    },
  ],
  assemblies: [
    {
      id: "assembly-body",
      objectType: "assembly",
      basisObjectType: "composite-object",
      role: "body",
      children: [
        "panel-bottom",
        "panel-side-left",
        "panel-side-right",
        "panel-top",
        "panel-back",
        "panel-shelf-1",
        "support-leg-front-left",
        "support-leg-front-center",
        "support-leg-front-right",
        "support-leg-back-left",
        "support-leg-back-center",
        "support-leg-back-right",
      ],
      contacts: [
        {
          id: "contact-side-left-bottom",
          panelId: "panel-side-left",
          restsOnPanelId: "panel-bottom",
          contactType: "vertical-panel-on-horizontal-panel",
          fasteningDirection: "from-bottom",
          requiresFasteners: true,
        },
        {
          id: "contact-side-right-bottom",
          panelId: "panel-side-right",
          restsOnPanelId: "panel-bottom",
          contactType: "vertical-panel-on-horizontal-panel",
          fasteningDirection: "from-bottom",
          requiresFasteners: true,
        },
        {
          id: "contact-top-between-sides",
          panelId: "panel-top",
          restsOnPanelId: "panel-side-left",
          contactType: "vertical-panel-on-horizontal-panel",
          fasteningDirection: "from-side",
          requiresFasteners: true,
        },
      ],
    },
    {
      id: "assembly-facade-block",
      objectType: "assembly",
      basisObjectType: "composite-object",
      role: "facade-block",
      children: [
        "panel-facade-left",
        "panel-facade-right",
        "hardware-hinge-left-1",
        "hardware-hinge-left-2",
        "hardware-hinge-right-1",
        "hardware-hinge-right-2",
      ],
      contacts: [],
    },
  ],
  edgeBanding: [
    { id: "edge-bottom-front", objectType: "edgeBanding", panelId: "panel-bottom", side: "front", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 1768, visible: true, basisOperation: "apply-edge" },
    { id: "edge-bottom-back", objectType: "edgeBanding", panelId: "panel-bottom", side: "back", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 1768, visible: false, basisOperation: "apply-edge" },
    { id: "edge-bottom-left", objectType: "edgeBanding", panelId: "panel-bottom", side: "left", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 600, visible: false, basisOperation: "apply-edge" },
    { id: "edge-bottom-right", objectType: "edgeBanding", panelId: "panel-bottom", side: "right", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 600, visible: false, basisOperation: "apply-edge" },
    { id: "edge-side-left-front", objectType: "edgeBanding", panelId: "panel-side-left", side: "front", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 2384, visible: true, basisOperation: "apply-edge" },
    { id: "edge-side-left-back", objectType: "edgeBanding", panelId: "panel-side-left", side: "back", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 2384, visible: false, basisOperation: "apply-edge" },
    { id: "edge-side-left-top", objectType: "edgeBanding", panelId: "panel-side-left", side: "top", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 600, visible: false, basisOperation: "apply-edge" },
    { id: "edge-side-left-bottom", objectType: "edgeBanding", panelId: "panel-side-left", side: "bottom", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 600, visible: false, basisOperation: "apply-edge" },
    { id: "edge-side-right-front", objectType: "edgeBanding", panelId: "panel-side-right", side: "front", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 2384, visible: true, basisOperation: "apply-edge" },
    { id: "edge-side-right-back", objectType: "edgeBanding", panelId: "panel-side-right", side: "back", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 2384, visible: false, basisOperation: "apply-edge" },
    { id: "edge-side-right-top", objectType: "edgeBanding", panelId: "panel-side-right", side: "top", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 600, visible: false, basisOperation: "apply-edge" },
    { id: "edge-side-right-bottom", objectType: "edgeBanding", panelId: "panel-side-right", side: "bottom", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 600, visible: false, basisOperation: "apply-edge" },
    { id: "edge-top-front", objectType: "edgeBanding", panelId: "panel-top", side: "front", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 1768, visible: true, basisOperation: "apply-edge" },
    { id: "edge-top-back", objectType: "edgeBanding", panelId: "panel-top", side: "back", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 1768, visible: false, basisOperation: "apply-edge" },
    { id: "edge-top-left", objectType: "edgeBanding", panelId: "panel-top", side: "left", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 600, visible: false, basisOperation: "apply-edge" },
    { id: "edge-top-right", objectType: "edgeBanding", panelId: "panel-top", side: "right", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 600, visible: false, basisOperation: "apply-edge" },
    { id: "edge-shelf-1-front", objectType: "edgeBanding", panelId: "panel-shelf-1", side: "front", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 860, visible: true, basisOperation: "apply-edge" },
    { id: "edge-shelf-1-back", objectType: "edgeBanding", panelId: "panel-shelf-1", side: "back", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 860, visible: false, basisOperation: "apply-edge" },
    { id: "edge-shelf-1-left", objectType: "edgeBanding", panelId: "panel-shelf-1", side: "left", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 554, visible: false, basisOperation: "apply-edge" },
    { id: "edge-shelf-1-right", objectType: "edgeBanding", panelId: "panel-shelf-1", side: "right", materialRef: "edge-white-abs-1mm", thicknessMm: 1, lengthMm: 554, visible: false, basisOperation: "apply-edge" },
    { id: "edge-facade-left-top", objectType: "edgeBanding", panelId: "panel-facade-left", side: "top", materialRef: "edge-white-abs-2mm", thicknessMm: 2, lengthMm: 894, visible: true, basisOperation: "apply-edge" },
    { id: "edge-facade-left-right", objectType: "edgeBanding", panelId: "panel-facade-left", side: "right", materialRef: "edge-white-abs-2mm", thicknessMm: 2, lengthMm: 2397, visible: true, basisOperation: "apply-edge" },
    { id: "edge-facade-left-bottom", objectType: "edgeBanding", panelId: "panel-facade-left", side: "bottom", materialRef: "edge-white-abs-2mm", thicknessMm: 2, lengthMm: 894, visible: true, basisOperation: "apply-edge" },
    { id: "edge-facade-left-left", objectType: "edgeBanding", panelId: "panel-facade-left", side: "left", materialRef: "edge-white-abs-2mm", thicknessMm: 2, lengthMm: 2397, visible: true, basisOperation: "apply-edge" },
    { id: "edge-facade-right-top", objectType: "edgeBanding", panelId: "panel-facade-right", side: "top", materialRef: "edge-white-abs-2mm", thicknessMm: 2, lengthMm: 894, visible: true, basisOperation: "apply-edge" },
    { id: "edge-facade-right-right", objectType: "edgeBanding", panelId: "panel-facade-right", side: "right", materialRef: "edge-white-abs-2mm", thicknessMm: 2, lengthMm: 2397, visible: true, basisOperation: "apply-edge" },
    { id: "edge-facade-right-bottom", objectType: "edgeBanding", panelId: "panel-facade-right", side: "bottom", materialRef: "edge-white-abs-2mm", thicknessMm: 2, lengthMm: 894, visible: true, basisOperation: "apply-edge" },
    { id: "edge-facade-right-left", objectType: "edgeBanding", panelId: "panel-facade-right", side: "left", materialRef: "edge-white-abs-2mm", thicknessMm: 2, lengthMm: 2397, visible: true, basisOperation: "apply-edge" },
  ],
  grooves: [],
  hardware: [
    {
      id: "hardware-hinge-left-1",
      objectType: "hardware",
      basisObjectType: "furniture-component",
      type: "hinge",
      supplier: "Firmax",
      series: "Smartline",
      doorType: "overlay",
      facadePanelId: "panel-facade-left",
      mountingPanelId: "panel-side-left",
      openingAngleDeg: 105,
      cupDiameterMm: 35,
      minCupDepthMm: 12,
      requiresTechnologistCheck: true,
    },
    {
      id: "hardware-hinge-left-2",
      objectType: "hardware",
      basisObjectType: "furniture-component",
      type: "hinge",
      supplier: "Firmax",
      series: "Smartline",
      doorType: "overlay",
      facadePanelId: "panel-facade-left",
      mountingPanelId: "panel-side-left",
      openingAngleDeg: 105,
      cupDiameterMm: 35,
      minCupDepthMm: 12,
      requiresTechnologistCheck: true,
    },
    {
      id: "hardware-hinge-right-1",
      objectType: "hardware",
      basisObjectType: "furniture-component",
      type: "hinge",
      supplier: "Firmax",
      series: "Smartline",
      doorType: "overlay",
      facadePanelId: "panel-facade-right",
      mountingPanelId: "panel-side-right",
      openingAngleDeg: 105,
      cupDiameterMm: 35,
      minCupDepthMm: 12,
      requiresTechnologistCheck: true,
    },
    {
      id: "hardware-hinge-right-2",
      objectType: "hardware",
      basisObjectType: "furniture-component",
      type: "hinge",
      supplier: "Firmax",
      series: "Smartline",
      doorType: "overlay",
      facadePanelId: "panel-facade-right",
      mountingPanelId: "panel-side-right",
      openingAngleDeg: 105,
      cupDiameterMm: 35,
      minCupDepthMm: 12,
      requiresTechnologistCheck: true,
    },
  ],
  drilling: [],
  supports: [
    {
      id: "support-leg-front-left",
      objectType: "support",
      mode: "adjustable-leg-60",
      heightMm: 60,
      hardwareRequired: true,
      affectsBodyGeometry: true,
      requiresTechnologistCheck: false,
      mountingPanelId: "panel-bottom",
    },
    {
      id: "support-leg-front-right",
      objectType: "support",
      mode: "adjustable-leg-60",
      heightMm: 60,
      hardwareRequired: true,
      affectsBodyGeometry: true,
      requiresTechnologistCheck: false,
      mountingPanelId: "panel-bottom",
    },
    {
      id: "support-leg-front-center",
      objectType: "support",
      mode: "adjustable-leg-60",
      heightMm: 60,
      hardwareRequired: true,
      affectsBodyGeometry: true,
      requiresTechnologistCheck: false,
      mountingPanelId: "panel-bottom",
    },
    {
      id: "support-leg-back-left",
      objectType: "support",
      mode: "adjustable-leg-60",
      heightMm: 60,
      hardwareRequired: true,
      affectsBodyGeometry: true,
      requiresTechnologistCheck: false,
      mountingPanelId: "panel-bottom",
    },
    {
      id: "support-leg-back-right",
      objectType: "support",
      mode: "adjustable-leg-60",
      heightMm: 60,
      hardwareRequired: true,
      affectsBodyGeometry: true,
      requiresTechnologistCheck: false,
      mountingPanelId: "panel-bottom",
    },
    {
      id: "support-leg-back-center",
      objectType: "support",
      mode: "adjustable-leg-60",
      heightMm: 60,
      hardwareRequired: true,
      affectsBodyGeometry: true,
      requiresTechnologistCheck: false,
      mountingPanelId: "panel-bottom",
    },
  ],
  basisManualPlan: [
    {
      id: "basis-step-create-panels",
      type: "create-panels",
      status: "manual",
      description: "Создать панели по списку panels",
    },
    {
      id: "basis-step-apply-materials",
      type: "apply-materials",
      status: "manual",
      description: "Назначить материалы и направление текстуры",
    },
    {
      id: "basis-step-apply-edge",
      type: "apply-edge",
      status: "manual",
      description: "Нанести кромку по edgeBanding",
    },
    {
      id: "basis-step-technologist-review",
      type: "technologist-review",
      status: "required",
      description: "Проверить пазы, присадку, фурнитуру и сборку",
    },
  ],
  validation: {
    errors: [],
    warnings: [
      {
        code: "drilling-not-finalized",
        severity: "warning",
        visibleToClient: false,
        requiresTechnologistCheck: true,
        message: "Присадка не финализирована и требует проверки технологом",
      },
    ],
  },
  review: {
    visibleToClient: false,
    requiresTechnologistCheck: true,
    status: "manual-review-required",
  },
  revisions: [],
};
